---
- name: test for ip
  ansible.builtin.shell: |
    set -e -o pipefail 
    ifconfig | grep {{ keepalived_virtual_ip }}
  failed_when: false
  register: ip_out
  changed_when: false
  args:
    executable: /bin/bash
- name: call set_route if we are on master instance
  ansible.builtin.command: /usr/local/bin/set_route {{ keepalived_ip }}
  when: ip_out.rc == 0
