---
- name: test for ip
  ansible.builtin.shell: |
    set -e -o pipefail 
    ifconfig | grep {{ keepalived_verify_virtual_ip }}
  failed_when: false
  register: ip_out
  changed_when: false
  args:
    executable: /bin/bash
- name: call set_route if we are on master instance
  ansible.builtin.command: '{{ keepalived_set_route_script_path }} {{ keepalived_ip }} {{ keepalived_script_subnet }}'
  when: ip_out.rc == 0
