---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
- name: restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
  when: keepalived_running
