---
- name: create directory
  ansible.builtin.file:
    path: /etc/keepalived
    state: directory
    owner: root
    group: root
    mode: 0644

- name: keepalive template
  ansible.builtin.template:
    src: '{{ keepalived_config_template }}'
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart keepalived

- name: Create systemd unit file
  ansible.builtin.template:
    src: keepalived.service.j2
    dest: /etc/systemd/system/keepalived.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd

- name: flush handlers
  meta: flush_handlers

- name: enable and start
  ansible.builtin.service:
    name: keepalived
    enabled: yes
    state: started
