---
#- name: set ip forward
#  ansible.posix.sysctl:
#    name: net.ipv4.ip_forward
#    value: '1'
#    sysctl_set: yes
#    state: present
#    reload: yes
- name: set ip nonlocal bind
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
